---
# Создаём архив аккаунта на Let's Encrypt
- name: "Create archive for acme.conf"
  become: true
  ansible.builtin.archive:
    path: "{{ create_le_backup_src }}/acme.config"
    dest: "/tmp/lebackup_conf.tar.gz"

# Создаём архив с сертификатами
- name: "Create archive for certs"
  become: true
  ansible.builtin.archive:
    path: "{{ create_le_backup_src }}/certs"
    dest: "/tmp/lebackup_certs.tar.gz"

# Выкачиваем acme.conf архив на локальную машину
- name: "Download 'acme.conf' archive to local machine"
  become: true
  ansible.builtin.fetch:
    flat: true
    src: "/tmp/lebackup_conf.tar.gz"
    dest: "{{ create_le_backup_dest }}/lebackup_conf.tar.gz"
    owner: root
    mode: "0600"

# Выкачиваем архив сертификатов на локальную машину
- name: "Download certificates archive to local machine"
  become: true
  ansible.builtin.fetch:
    flat: true
    src: "/tmp/lebackup_certs.tar.gz"
    dest: "{{ create_le_backup_dest }}/lebackup_certs.tar.gz"
    owner: root
    mode: "0600"
