---
# Без фаервола, как голышом на званом
# вечере - можно, но не прилично.
- name: "Install firewalld"
  become: true
  ansible.builtin.dnf:
    name:
      - firewalld
  notify: "Enable firewalld service"

# Запускаем фаервол
- name: "Run handlers"
  ansible.builtin.meta:
    flush_handlers

# Устанавливаем маленькие, но полезные утилиты,
# без которых часть ролей не работает
# Последние две для облегчения отладки и русского
# языка в консоли вместо кракозябр
- name: "Install supplementary tools"
  become: true
  ansible.builtin.dnf:
    name:
      - net-tools
      - wget
      - nano
      - unzip
      - python3-firewall
      - policycoreutils-python-utils
      - rsync
      - glibc-all-langpacks
      - mc
    state: present

# Как же он меня задрал своими
# ударами в спину изподтишка
- name: "Disable SElinux"
  become: true
  ansible.builtin.copy:
    src: "files/config"
    dest: "/etc/selinux/config"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Disable SElinux now"
  block:
    - name: "Try to disable SElinux NOW!!!"
      become: true
      ansible.builtin.command:
        cmd: "setenforce 0"
  rescue:
    - name: "Hooray!!!"
      ansible.builtin.debug:
        msg: "SElinux already disabled?! Wow!!!"

# Создаем локальную зону "home", куда пускают только
# с локальных IP
- name: "Add local IPs to 'home' zone in firewall"
  become: true
  ansible.posix.firewalld:
    zone: "home"
    source: "{{ ansible_default_ipv4.address.split('.')[0] }}.{{ ansible_default_ipv4.address.split('.')[1] }}.0.0/16"
    state: "enabled"
    permanent: true
    immediate: true
