---
- name: "Role *install_common* starting..."
  ansible.builtin.debug:
    msg: "*install_common* role starting..."

- name: "Install firewalld"
  become: true
  ansible.builtin.dnf:
    name:
      - firewalld
  notify: "Enable firewalld service"

- name: "Run handlers"
  ansible.builtin.meta:
    flush_handlers

- name: "Install supplementary tools"
  become: true
  ansible.builtin.dnf:
    name:
      - net-tools
      - wget
      - nano
      - unzip
      - python3-firewall
      - policycoreutils-python-utils
    state: present

- name: "Add local IPs to 'home' zone in firewall"
  ansible.posix.firewalld:
    zone: "home"
    source: "{{ ansible_default_ipv4.address.split('.')[0] }}.{{ ansible_default_ipv4.address.split('.')[1] }}.0.0/16"
    state: "enabled"
    permanent: true
    immediate: true
