---
# Создаём каталог для ключей,
# если он ещё не создан
- name: "Create target dir"
  become: true
  ansible.builtin.file:
    path: "{{ setup_cicd_glrunner_key_dir_dest }}"
    state: "directory"
    owner: "gitlab-runner"
    group: "gitlab-runner"
    mode: "0700"

# Копируем приватный ssh-ключ в каталог,
# доступный GitLab-раннеру
- name: "Copy private SSH-key"
  become: true
  ansible.builtin.copy:
    src: "{{ setup_cicd_glrunner_key_dir_src }}/{{ setup_cicd_glrunner_key_name }}"
    dest: "{{ setup_cicd_glrunner_key_dir_dest }}/"
    owner: "gitlab-runner"
    group: "gitlab-runner"
    mode: "0400"
    remote_src: true

# Копируем публичный ssh-ключ в каталог,
# доступный GitLab-раннеру
- name: "Copy public SSH-key"
  become: true
  ansible.builtin.copy:
    src: "{{ setup_cicd_glrunner_key_dir_src }}/{{ setup_cicd_glrunner_key_name }}.pub"
    dest: "{{ setup_cicd_glrunner_key_dir_dest }}/"
    owner: "gitlab-runner"
    group: "gitlab-runner"
    mode: "0644"
    remote_src: true

# Копируем конфигурацию ssh в каталог,
# доступный GitLab-раннеру
- name: "Copy config SSH"
  become: true
  ansible.builtin.copy:
    src: "{{ setup_cicd_glrunner_key_dir_src }}/config"
    dest: "{{ setup_cicd_glrunner_key_dir_dest }}/"
    owner: "gitlab-runner"
    group: "gitlab-runner"
    mode: "0644"
    remote_src: true

# Даём gitlab-runner'у sudo без пароля
- name: "Enable passwordless sudo for gitlab-runner"
  become: true
  ansible.builtin.shell:
    cmd: 'sudo bash -c "echo \"gitlab-runner ALL=(ALL)  NOPASSWD: ALL\" >> /etc/sudoers"'
  changed_when: false
