---
- name: "Restore Let's Encrypt account data from local backup to proxy"
  block:
    - name: "Try to restore acme.conf from local backup to proxy"
      become: true
      ansible.builtin.unarchive:
        src: "{{ restore_le_backup_src }}/lebackup_conf.tar.gz"
        dest: "{{ restore_le_backup_dest }}"
  rescue:
    - name: "We have no backup of acme.conf yet :("
      ansible.builtin.debug:
        msg: "We have no backup of acme.conf yet :("

- name: "Restore Let's Encrypt certificates from local backup to proxy"
  block:
    - name: "Try to restore certificates from local backup to proxy"
      become: true
      ansible.builtin.unarchive:
        src: "{{ restore_le_backup_src }}/lebackup_certs.tar.gz"
        dest: "{{ restore_le_backup_dest }}"
  rescue:
    - name: "We have no backup of certificates yet :( "
      ansible.builtin.debug:
        msg: "We have no backup of certificates yet :( "

