---
- name: "Install nginx"
  become: true
  ansible.builtin.dnf:
    name:
      - "@nginx:{{ install_nginx_ver }}/common"
    state: present
  notify: "Setup nginx service"

- name: "Create web directory"
  become: true
  ansible.builtin.file:
    path: "{{ install_nginx_web_dir }}"
    state: directory
    owner: "nginx"
    group: "nginx"
    mode: "0755"

- name: "Flush handlers"
  ansible.builtin.meta:
    flush_handlers
