---
# Ждём, пока сервак очухается
# раз в 5 секунд опрашиваяя его по HTTPS
# На ожидание даётся, максимум, 10 минут
- name: "Wait for GitLab-server"
  become: true
  ansible.builtin.wait_for:
    port: "443"
    host: "{{ setup_glrunner_srv_ip }}"
    delay: "20"
    sleep: "5"
    timeout: "600"

# Сразу не ломимся - прокси 502 ошибку выдаст,
# лучше ещё 10 секунд подождать
- name: "Wait 10s"
  ansible.builtin.wait_for:
    timeout: "10"

# Задаём параметры раннера
- name: "Setup GitLab runner"
  become: true
  ansible.builtin.command:
    cmd: >
      gitlab-runner register
      --non-interactive
      --url "{{ setup_glrunner_srv_url }}"
      --registration-token "{{ setup_glrunner_token }}"
      --executor "{{ setup_glrunner_executor }}"
      --docker-image "{{ setup_glrunner_docker_img }}"
      --description "{{ setup_glrunner_description }}"
      --maintenance-note "{{ setup_glrunner_maintenance }}"
      --tag-list "{{ setup_glrunner_tags }}"
      --run-untagged="{{ setup_glrunner_run_untagged }}"
      --locked="{{ setup_glrunner_locked }}"
      --access-level="{{ setup_glrunner_access_lvl }}"
  changed_when: false
