resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [nodes:children]
    proxy

    [proxy]
    ${yandex_compute_instance.proxy.fqdn} ansible_host=${yandex_compute_instance.proxy.network_interface.0.nat_ip_address}

    DOC
  filename = "../ansible/inventory"

  depends_on = [
    yandex_compute_instance.proxy
#    yandex_compute_instance.node02,
#    yandex_compute_instance.node03,
#    yandex_compute_instance.node04,
#    yandex_compute_instance.node05,
#    yandex_compute_instance.node06
  ]
}
