---
- name: "Role *install_squid* starting..."
  ansible.builtin.debug:
    msg: "*install_squid* role starting..."

# Устанавливаем Squid
- name: "Install Squid-proxy"
  become: true
  ansible.builtin.dnf:
    name:
      - squid
    state: present
  notify: "Start squid service"

# Прописываем Squid'у в конфигах,
# что всем можно качать всё
- name: "Copy squid config (allow ALL)"
  become: true
  ansible.builtin.template:
    src: "templates/squid.conf.j2"
    dest: "/etc/squid/squid.conf"
    owner: "root"
    group: "root"
    mode: "0644"

# Запускаем Squid
- name: "Flush handlers"
  ansible.builtin.meta:
    flush_handlers

# Открываем на доступ из локальной сети
# порт 3128
- name: "Enable firewall for proxy access"
  become: true
  ansible.posix.firewalld:
    zone: "home"
    service: "squid"
    state: "enabled"
    permanent: true
    immediate: true
