---
# Эта роль жёстко задана под дипломную конфигурацию
# никаких переменных, всё прибьём гвоздями

# Настраиваем Prometheus
- name: "Prometheus setup"
  become: true
  ansible.builtin.template:
    src: "templates/prometheus.yml.j2"
    dest: "/etc/prometheus/prometheus.yml"
    owner: "root"
    group: "root"
    mode: "0644"

# Скармливаем ему правила для AlertManager'а
- name: "Alert Manager setup"
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/prometheus/"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - "files/alerts_node_exporter.yml"
    - "files/alerts_prometheus.yml"

# Перезапускаем его нафиг
- name: "Restart Prometheus"
  become: true
  ansible.builtin.systemd:
    name: "prometheus.service"
    state: "restarted"
