---
- name: "Setup proxy settings"
  ansible.builtin.debug:
    msg: [
      "Proxy will be configured with next settings:",
      "{{ setup_proxy_protocol }}{{ setup_proxy_fqdn }}:{{ setup_proxy_port }}"
    ]

# Заставляем dnf работать через прокси
- name: "Replace DNF-config"
  become: true
  ansible.builtin.template:
    backup: true
    src: "templates/dnf.j2"
    dest: "/etc/dnf/dnf.conf"
    owner: "root"
    group: "root"
    mode: "0644"

# Заставляем wget работать через прокси
- name: "Replace wget-config"
  become: true
  ansible.builtin.template:
    backup: true
    src: "templates/wgetrc.j2"
    dest: "/etc/wgetrc"
    owner: "root"
    group: "root"
    mode: "0644"

# Задаём в глообальных системных установках
# использовать прокси
- name: "Set global system proxy settings"
  become: true
  ansible.builtin.template:
    backup: true
    src: "templates/set_proxy.sh.j2"
    dest: "/etc/profile.d/set_proxy.sh"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "Run proxy-script"
  ansible.builtin.command:
    cmd: "/etc/profile.d/set_proxy.sh"
  when: true
