---
# Устанавливаем заданную версию PHP
- name: "Install php"
  become: true
  ansible.builtin.dnf:
    name: "{{ install_php_packages }}"
    state: present
  notify: "Setup php-fpm service"

# (Не) запускаем php-fpm сервис
# (от настроек зависит)
- name: "Flush handlers"
  ansible.builtin.meta:
    flush_handlers
