---
# Устанавливаем общее ПО для хостов из группы
# Pass4 (Monitoring)
- name: "Common setup part for Pass4 hosts"
  hosts: Pass4
  gather_facts: true
  become: true
  become_user: "root"
  remote_user: "cloud-user"
  roles:
    - role: setup_proxy_dnf                     # Все хосты, кроме прокси, доступа к интернету напрямую не имеют
      vars:                                     # Обучаем несчастных работать через прокси
        setup_proxy_fqdn: "{{ tf_proxy_name }}"
        setup_proxy_port: "{{ tf_proxy_port }}"
    - role: deploy_ssh_keys                     # Заливаем SSH-ключи
      vars:
        deploy_ssh_keys_priv_dir: "./ssh"
        deploy_ssh_keys_priv_key: "rsync.key"
        deploy_ssh_keys_trusted_domain: "{{ tf_my_domain_tld }}"
        deploy_ssh_keys_owner: "cloud-user"
        deploy_ssh_keys_target_dir: "/home/cloud-user/.ssh"
    - role: install_common                      # Ставим комплект необходимых утилит

- name: "Install monitoring"
  hosts: Monitoring
  gather_facts: false
  become: true
  become_user: "root"
  remote_user: "cloud-user"
  roles:
    - role: install_node_exporter
    - role: install_prometheus