---
- name: "Install common tools"
  hosts: Proxies
  gather_facts: true
  become: true
  become_user: "root"
  remote_user: "cloud-user"
  roles:
    - role: install_common

- name: "Install proxy"
  hosts: Proxies
  gather_facts: false
  become: true
  become_user: "root"
  remote_user: "cloud-user"
  roles:
    - role: install_squid
    - role: install_proxy
      vars:
        proxy_my_domain_tld: "{{ tf_my_domain_tld }}"
        proxy_tf_workspace: "{{ tf_workspace }}"
