---
- name: "Reconfigure DNF to use proxy"
  hosts: Pass2
  gather_facts: false
  become: true
  become_user: "root"
  remote_user: "cloud-user"
  roles:
    - role: setup_proxy_dnf
      vars:
        proxy_fqdn: "{{ proxy_name }}"

- name: "Install common tools"
  hosts: Pass2
  gather_facts: true
  become: true
  become_user: "root"
  remote_user: "cloud-user"
  roles:
    - role: install_common

- name: "Install Database-servers"
  hosts: Databases
  gather_facts: true
  become: true
  become_user: "root"
  remote_user: "cloud-user"
  roles:
    - role: install_mariadb
    - role: setup_cluster
      vars:
        cluster_master: "{{ db_master }}"
    - role: setup_db
      vars:                                # неохота мне еще и явки/пароли вордпресса в переменные выносить
        setup_db_host: "{{ db_master }}"
        setup_db_name: "wordpress"
        setup_db_owner_user: "wordpress"
        setup_db_owner_pass: "wordpress"

# - name: "Install Wordpress-server"
#   hosts: Wordpress
#   gather_facts: false
