---
# Создаём SSH-ключи, которые пригодятся для обмена
# данными между компами в локальной сети
- name: "Generate SSH-certs"
  hosts: localhost
  gather_facts: false
  roles:
    - role: generate_ssh_keypair
      vars:
        generate_ssh_keypair_algo: "ed25519"
        generate_ssh_keypair_bit_size: "4096"
        generate_ssh_keypair_dir: "./ssh"
        generate_ssh_keypair_filename: "rsync.key"
        generate_ssh_keypair_comment: "cloud-user@{{ tf_my_domain_tld }}"

# Пакет ролей для установки (реверс) прокси сервера
- name: "Install (reverse)-proxy server"
  hosts: Proxies
  gather_facts: true
  roles:
    - role: install_common                            # Установка набора полезных утилит
    - role: deploy_ssh_keys                           # Загружаем SSH-ключи в прокси
      vars:
        deploy_ssh_keys_priv_dir: "./ssh"
        deploy_ssh_keys_priv_key: "rsync.key"
        deploy_ssh_keys_trusted_domain: "{{ tf_my_domain_tld }}"
        deploy_ssh_keys_owner: "cloud-user"
        deploy_ssh_keys_target_dir: "/home/cloud-user/.ssh"
    - role: install_squid                             # Устанавливаем Squid-прокси
    - role: install_proxy                             # Устанавливаем всё остальное
      vars:
        proxy_my_domain_tld: "{{ tf_my_domain_tld }}"
