---
- name: "Install common tools"
  hosts: all
  gather_facts: false
  become: true
  become_user: "root"
  remote_user: "cloud-user"
  roles:
    - install_common

- name: "Install proxy"
  hosts: ProxiesDisabled
  gather_facts: true
  become: true
  become_user: "root"
  remote_user: "cloud-user"
  roles:
    - role: install_proxy
      vars:
        proxy_my_domain_tld: "{{ ansible_domain }}"
