---
- name: "Install common tools"
  hosts: all
  gather_facts: true
  become: true
  become_user: "root"
  remote_user: "cloud-user"
  roles:
    - role: install_common

- name: "Install proxy"
  hosts: Proxies
  gather_facts: true
  become: true
  become_user: "root"
  remote_user: "cloud-user"
  roles:
    - role: install_proxy
      vars:
        proxy_my_domain_tld: "{{ ansible_domain }}"

- name: "Install databases"
  hosts: Databases
  gather_facts: true
  become: true
  become_user: "root"
  remote_user: "cloud-user"
  roles:
    - role: install_mariadb
    - role: setup_cluster
      vars:
        cluster_master: "{{ db_master }}"
