---
- name: "Install common tools"
  hosts: all
  gather_facts: false
  become: true
  become_user: "root"
  remote_user: "cloud-user"
  roles:
    - install_tools

- name: "Install proxy"
  hosts: proxy
  gather_facts: false
  become: true
  become_user: "root"
  remote_user: "cloud-user"
  roles:
    - install_proxy
