---
- name: "Generate token"
  hosts: localhost
  gather_facts: false
  become: true
  become_user: "root"
  remote_user: "root"
  roles:
    - role: generate_token
      vars:
        generate_token_filepath: "./ssh/token"

- name: "Install squid for GitLab on Test2"
  hosts: Test2
  gather_facts: true
  become: true
  become_user: "root"
  remote_user: "cloud-user"
  roles:
    - role: install_common
    - role: install_squid

- name: "Test_install_gitlab on Test"
  hosts: Test
  gather_facts: true
  become: true
  become_user: "root"
  remote_user: "cloud-user"
  roles:
    - role: generate_token
    - role: setup_proxy_dnf
      vars:
        setup_proxy_fqdn: "test2.bfg-10k.ru"
        setup_proxy_protocol: "http://"
        setup_proxy_port: "3128"
    - role: install_common
    - role: install_gitlab
      vars:
        install_gitlab_external_url: "https://gltest.bfg-10k.ru"
        install_gitlab_root_pass: "DukeNukemMustDie!!!"
        install_gitlab_runner_token: "{{ lookup('ansible.builtin.file', './ssh/token') }}"
        install_gitlab_proxy_internal_ip: "192.168.1.98"
        install_gitlab_proxy_url: "http://test2.bfg-10k.ru:3128"
        install_gitlab_ca_cert: "/opt/LEscript/certs/bfg-10k.ru/ca.cer"
        install_gitlab_fullchain_cert: "/opt/LEscript/certs/bfg-10k.ru/fullchain.cer"
        install_gitlab_cert_key: "/opt/LEscript/certs/bfg-10k.ru/bfg-10k.ru.key"

- name: "Test_install_runner on Test2"
  hosts: Test2
  gather_facts: false
  become: true
  become_user: "root"
  remote_user: "cloud-user"
  roles:
    - role: install_glrunner
    - role: setup_glrunner
      vars:
        setup_glrunner_token: "{{ lookup('ansible.builtin.file', './ssh/token') }}"
        setup_glrunner_host_url: "https://test.bfg-10k.ru"
        setup_glrunner_executor: "docker"
