---
# Устанавливаем MariaDB сервер
- name: "Install MariaDB server"
  become: true
  ansible.builtin.dnf:
    name:
      - mariadb-server
      - python3-PyMySQL
    state: present
  notify: "Enable mariadb service"

# Открываем доступ к нему через фаервол
- name: "Setup firewall for MySQL"
  become: true
  ansible.posix.firewalld:
    zone: "home"
    service: "mysql"
    state: "enabled"
    permanent: true
    immediate: true

# Запускаем сервис MariaDB
- name: "Flush handlers"
  ansible.builtin.meta:
    flush_handlers
